//! The MCP tool surface exposed to hosted Claude sessions.
//!
//! [`TermherdMcp`] is an rmcp [`ServerHandler`]: it answers `tools/list` and
//! `tools/call` for the live-bridge tools. Each tool is a thin adapter — it
//! translates the call into a [`Request`] on the async-transport bridge, awaits
//! the timeout-bounded [`Reply`], and shapes it back into an MCP result. No state
//! and no `core` access live here; the shell owns `core::App` and answers on the
//! bridge, so a tool can never touch it directly.

use std::time::Duration;

use rmcp::{
    ErrorData, ServerHandler,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::{CallToolResult, Implementation, ProtocolVersion, ServerCapabilities, ServerInfo},
    schemars::JsonSchema,
    tool, tool_handler, tool_router,
};
use serde::{Deserialize, Serialize};
use termherd_core::snapshot::DEFAULT_TEXT_LINES;
use termherd_core::workspace::SplitDir;
use termherd_core::{Section, SessionStatus, SnapshotFilter, TerminalScope};

use crate::shell::bridge::{
    Action, BridgeHandle, CallError, Reply, Request, SessionInfo, SessionKind,
};
use crate::snapshot_dto::{SnapshotDto, status_str};

/// How long a tool waits for the shell to answer before failing the caller.
/// Bounds the whole round-trip (enqueue + reply) via [`BridgeHandle::call`], so
/// a wedged shell surfaces as a tool error, never a hang (Q7).
const CALL_TIMEOUT: Duration = Duration::from_secs(5);

/// Default bound for `wait_for_status` when the caller names none. Long enough
/// for a real command, short enough that a forgotten wait reports back.
const DEFAULT_WAIT_MS: u64 = 30_000;

/// Hard cap on a wait, whatever the caller asks for — the outer Q7 guarantee
/// that no bridge call can park a caller indefinitely.
const MAX_WAIT_MS: u64 = 300_000;

/// Bound on the status read-back after a wait timed out. Deliberately short: it
/// is a courtesy on top of an answer the caller has already earned, so it must
/// barely extend the wait it follows.
const READ_BACK_TIMEOUT: Duration = Duration::from_millis(250);

/// The live-bridge MCP server handler. Holds only the bridge into the shell —
/// cloned fresh per session by the transport's service factory.
#[derive(Clone)]
pub struct TermherdMcp {
    bridge: BridgeHandle,
    tool_router: ToolRouter<Self>,
}

#[tool_router(router = tool_router)]
impl TermherdMcp {
    /// Build a handler over `bridge`. The tool router is generated by the
    /// `#[tool_router]` macro from the `#[tool]` methods below.
    pub fn new(bridge: BridgeHandle) -> Self {
        Self {
            bridge,
            tool_router: Self::tool_router(),
        }
    }

    /// The spike tool: list the live terminal sessions termherd is hosting, each
    /// with its stable handle, so an MCP client can address them.
    #[tool(
        name = "list_sessions",
        description = "List the live terminal sessions termherd is hosting. Each \
                       row carries a stable `handle` (address it in later calls), \
                       the tab title, working directory, kind (shell or claude), \
                       the resumed Claude id if any, and current activity status."
    )]
    async fn list_sessions(&self) -> Result<CallToolResult, ErrorData> {
        let reply = self
            .bridge
            .call(Request::ListSessions, CALL_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Sessions(sessions) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        let rows: Vec<SessionDto> = sessions.iter().map(SessionDto::from).collect();
        let value = serde_json::to_value(&rows)
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        Ok(CallToolResult::structured(value))
    }

    /// A filterable, read-only snapshot of the whole workspace — the structured
    /// "DOM" a client reads to perceive termherd before acting. Light by default
    /// (structure only, no terminal text); scope terminal text to named handles.
    #[tool(
        name = "snapshot",
        description = "A filterable snapshot of termherd's whole state: config, \
                       the session-browser sidebar, and the open tabs with their \
                       panes (each pane's stable handle, kind, cwd, status). Light \
                       by default — no terminal text. Args (all optional): \
                       `sections` (any of \"config\", \"sidebar\", \"tabs\"; omit \
                       for all), `terminals` (session handles to include screen \
                       text for; omit for none — read the structure first, then \
                       request a handle), `text_lines` (trailing lines per \
                       requested terminal, default 40)."
    )]
    async fn snapshot(
        &self,
        Parameters(args): Parameters<SnapshotArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let reply = self
            .bridge
            .call(Request::Snapshot(args.into_filter()), CALL_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Snapshot(snapshot) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        let value = serde_json::to_value(SnapshotDto::from(&snapshot))
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        Ok(CallToolResult::structured(value))
    }

    /// Open a new terminal session and focus it. → `open_session`.
    #[tool(
        name = "open_session",
        description = "Open a new terminal session and focus it. Args: `project` \
                       (working directory; omit for the home dir), `kind` \
                       (\"shell\" or \"claude\", default \"shell\"). Returns the \
                       new session's `focused_handle`."
    )]
    async fn open_session(
        &self,
        Parameters(args): Parameters<OpenArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let action = Action::Open {
            project: args.project,
            kind: match args.kind.as_deref() {
                None | Some("shell") => SessionKind::Shell,
                Some("claude") => SessionKind::Claude,
                Some(other) => {
                    return Err(ErrorData::invalid_params(
                        format!("unknown kind {other:?}; expected \"shell\" or \"claude\""),
                        None,
                    ));
                }
            },
        };
        self.act(action).await
    }

    /// Split a pane, opening a fresh session beside it. → `split_pane`.
    #[tool(
        name = "split_pane",
        description = "Split a pane, opening a fresh shell beside it and focusing \
                       it. Args: `direction` (\"vertical\" = side by side, \
                       \"horizontal\" = stacked; default \"vertical\"), `pane` \
                       (session handle to split; omit for the focused pane). \
                       Returns the new pane's `focused_handle`."
    )]
    async fn split_pane(
        &self,
        Parameters(args): Parameters<SplitArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let dir = match args.direction.as_deref() {
            None | Some("vertical") | Some("v") => SplitDir::Vertical,
            Some("horizontal") | Some("h") => SplitDir::Horizontal,
            Some(other) => {
                return Err(ErrorData::invalid_params(
                    format!("unknown direction {other:?}; expected \"vertical\" or \"horizontal\""),
                    None,
                ));
            }
        };
        let pane = parse_optional_handle(args.pane)?;
        self.act(Action::Split { pane, dir }).await
    }

    /// Move focus to the pane hosting a session. → `focus_pane`.
    #[tool(
        name = "focus_pane",
        description = "Move focus to the pane hosting a session, and hand it the \
                       keyboard. Args: `session` (its stable handle). Returns the \
                       resulting `focused_handle`."
    )]
    async fn focus_pane(
        &self,
        Parameters(args): Parameters<FocusArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let session = parse_handle(&args.session)?;
        self.act(Action::Focus { session }).await
    }

    /// Give a tab a manual name. → `rename_tab`.
    #[tool(
        name = "rename_tab",
        description = "Give the tab at `tab` (0-based index, as `snapshot` reports \
                       tab order) a manual name. A blank `title` reverts to the \
                       derived title. Returns the current `focused_handle`."
    )]
    async fn rename_tab(
        &self,
        Parameters(args): Parameters<RenameArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        self.act(Action::Rename {
            tab: args.tab,
            title: args.title,
        })
        .await
    }

    /// Close a pane; a lone pane closes its whole tab. → `close_pane`.
    #[tool(
        name = "close_pane",
        description = "Close a pane and kill its terminal. Args: `pane` (session \
                       handle to close; omit for the focused pane). A lone pane is \
                       its whole tab, which closes. Returns the resulting \
                       `focused_handle` (null when the workspace is now empty)."
    )]
    async fn close_pane(
        &self,
        Parameters(args): Parameters<CloseArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let pane = parse_optional_handle(args.pane)?;
        self.act(Action::Close { pane }).await
    }

    /// Type text into a session's terminal without waiting. → `run_in_session`.
    #[tool(
        name = "run_in_session",
        description = "Type text into a session's terminal, as if typed at the \
                       keyboard — does not wait for it to finish (read the result \
                       with `snapshot`'s scoped terminal text). Include a trailing \
                       newline in `text` to submit a command. Args: `session` (its \
                       stable handle), `text`. Returns the `focused_handle`."
    )]
    async fn run_in_session(
        &self,
        Parameters(args): Parameters<RunArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let session = parse_handle(&args.session)?;
        self.act(Action::Run {
            session,
            bytes: args.text.into_bytes(),
        })
        .await
    }

    /// Block until a session's activity reaches one of the given statuses — the
    /// synchronisation half of `act → wait → observe`.
    #[tool(
        name = "wait_for_status",
        description = "Wait until a session's activity reaches one of `statuses` \
                       (default: idle or attention), then report it. Pair it \
                       with `run_in_session`, which returns immediately: run, \
                       wait, then `read_terminal`. Args: `session` (handle), \
                       `statuses` (any of \"starting\", \"busy\", \"idle\", \
                       \"attention\", \"exited\"), `timeout_ms` (default 30000, \
                       capped at 300000). A session that exits settles the wait \
                       whatever you asked for — it can no longer reach it. \
                       Returns `{ status, timed_out }`: on timeout the status is \
                       the session's current one, not an error."
    )]
    async fn wait_for_status(
        &self,
        Parameters(args): Parameters<WaitArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let session = parse_handle(&args.session)?;
        let targets = parse_statuses(args.statuses)?;
        let timeout = wait_timeout(args.timeout_ms);

        match self
            .bridge
            .call(Request::WaitForStatus { session, targets }, timeout)
            .await
        {
            Ok(Reply::Waited(outcome)) => {
                if let Some(reason) = outcome.error {
                    return Err(ErrorData::invalid_params(reason, None));
                }
                Ok(CallToolResult::structured(serde_json::json!({
                    "status": outcome.status.map(status_str),
                    "timed_out": false,
                })))
            }
            Ok(_) => Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            )),
            // The wait outlived its bound. Report *where the session got to*
            // rather than a bare failure: an agent that waited 30s needs the
            // current status to decide whether to keep waiting or give up.
            Err(CallError::Timeout(_)) => {
                let status = self.current_status(session).await;
                Ok(CallToolResult::structured(serde_json::json!({
                    "status": status,
                    "timed_out": true,
                })))
            }
            Err(error) => Err(ErrorData::internal_error(error.to_string(), None)),
        }
    }

    /// The visible text of one session's terminal — the deep read `snapshot`
    /// deliberately leaves out.
    #[tool(
        name = "read_terminal",
        description = "Read the visible text of one session's terminal. Args: \
                       `session` (handle), `lines` (trailing lines to keep, \
                       default 40). Returns `{ text, rendered }`; `rendered` is \
                       false when the session is live but its screen has not \
                       been drawn yet — retry rather than giving up on the \
                       handle."
    )]
    async fn read_terminal(
        &self,
        Parameters(args): Parameters<ReadArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        let session = parse_handle(&args.session)?;
        let lines = args.lines.unwrap_or(DEFAULT_TEXT_LINES);
        let reply = self
            .bridge
            .call(Request::ReadTerminal { session, lines }, CALL_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Terminal(read) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        if let Some(reason) = read.error {
            return Err(ErrorData::invalid_params(reason, None));
        }
        Ok(CallToolResult::structured(serde_json::json!({
            "text": read.text.as_deref().unwrap_or_default(),
            "rendered": read.text.is_some(),
        })))
    }
}

impl TermherdMcp {
    /// A session's current activity, read back after a wait timed out. Best
    /// effort by design: `None` covers a handle that no longer resolves *and* a
    /// read-back that failed. The likeliest cause of the original timeout is a
    /// wedged shell, which would fail this call too — and turning that into an
    /// error would swallow the `timed_out` answer the caller is owed.
    async fn current_status(&self, session: u64) -> Option<&'static str> {
        match self
            .bridge
            .call(Request::ListSessions, READ_BACK_TIMEOUT)
            .await
        {
            Ok(Reply::Sessions(sessions)) => sessions
                .iter()
                .find(|info| info.handle == session.to_string())
                .map(|info| status_str(info.status)),
            Ok(_) => None,
            Err(error) => {
                tracing::debug!(%error, "could not read the status back after a wait timeout");
                None
            }
        }
    }

    /// Send an [`Action`] over the bridge and shape its [`ActionOutcome`] into a
    /// tool result: a rejection (unknown handle / out-of-range tab) becomes an
    /// `invalid_params` error, an applied action a `{ focused_handle }` object.
    async fn act(&self, action: Action) -> Result<CallToolResult, ErrorData> {
        let reply = self
            .bridge
            .call(Request::Act(action), CALL_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Acted(outcome) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        if let Some(reason) = outcome.error {
            return Err(ErrorData::invalid_params(reason, None));
        }
        let value = serde_json::json!({ "focused_handle": outcome.focused });
        Ok(CallToolResult::structured(value))
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for TermherdMcp {
    fn get_info(&self) -> ServerInfo {
        // rmcp's `ServerInfo`/`Implementation` are `#[non_exhaustive]`, so build
        // from a default and set the fields we care about rather than a literal.
        let mut server = Implementation::from_build_env();
        server.name = "termherd".into();
        server.version = env!("CARGO_PKG_VERSION").into();

        let mut info = ServerInfo::default();
        info.protocol_version = ProtocolVersion::LATEST;
        info.capabilities = ServerCapabilities::builder().enable_tools().build();
        info.server_info = server;
        info.instructions = Some(
            "termherd's live bridge: read and (later) drive the terminal \
             sessions it is hosting."
                .into(),
        );
        info
    }
}

/// The on-the-wire shape of a session for the `list_sessions` tool: the stable
/// external handle plus flat, string-typed fields an MCP client can read without
/// knowing termherd's internal enums.
#[derive(Serialize)]
struct SessionDto {
    /// Stable external handle (the runtime session id).
    handle: String,
    title: String,
    cwd: Option<String>,
    /// `"shell"` or `"claude"`.
    kind: &'static str,
    /// The resumed Claude session id, if any (the *unstable* id — never the
    /// handle).
    resume_id: Option<String>,
    /// `"starting"`, `"busy"`, `"idle"`, `"attention"`, or `"exited"`.
    status: &'static str,
}

impl From<&SessionInfo> for SessionDto {
    fn from(info: &SessionInfo) -> Self {
        Self {
            handle: info.handle.clone(),
            title: info.title.clone(),
            cwd: info.cwd.clone(),
            kind: match info.kind {
                SessionKind::Shell => "shell",
                SessionKind::Claude => "claude",
            },
            resume_id: info.resume_id.clone(),
            status: status_str(info.status),
        }
    }
}

/// The `snapshot` tool's arguments — every field optional so a bare call is the
/// light default. Deserialised from the MCP `arguments` object.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct SnapshotArgs {
    /// Sections to include: any of `"config"`, `"sidebar"`, `"tabs"`. Omit for
    /// all three. Unknown names are ignored.
    #[serde(default)]
    sections: Option<Vec<String>>,
    /// Session handles (as strings, as `list_sessions` reports them) to include
    /// terminal text for. Omit (or empty) for none.
    #[serde(default)]
    terminals: Option<Vec<String>>,
    /// Include the focused pane's terminal text — a one-call shortcut when you
    /// don't yet know its handle. Ignored when `terminals` names handles.
    #[serde(default)]
    focused_terminal: Option<bool>,
    /// Trailing terminal lines to keep per requested session.
    #[serde(default)]
    text_lines: Option<usize>,
}

impl SnapshotArgs {
    /// Map the flat MCP arguments onto the core [`SnapshotFilter`]. Omitted
    /// fields fall back to the light default. Explicit handles win over the
    /// `focused_terminal` shortcut.
    fn into_filter(self) -> SnapshotFilter {
        let default = SnapshotFilter::default();
        let sections = match self.sections {
            Some(names) => names
                .iter()
                .filter_map(|name| match name.as_str() {
                    "config" => Some(Section::Config),
                    "sidebar" => Some(Section::Sidebar),
                    "tabs" => Some(Section::Tabs),
                    _ => None,
                })
                .collect(),
            None => default.sections,
        };
        let terminals = match self.terminals {
            Some(handles) if !handles.is_empty() => {
                TerminalScope::Only(handles.iter().filter_map(|h| h.parse().ok()).collect())
            }
            _ if self.focused_terminal == Some(true) => TerminalScope::Focused,
            _ => TerminalScope::None,
        };
        SnapshotFilter {
            sections,
            terminals,
            text_lines: self.text_lines.unwrap_or(default.text_lines),
        }
    }
}

/// Arguments for `open_session`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct OpenArgs {
    /// Working directory for the new session. Omit for the home directory.
    #[serde(default)]
    project: Option<String>,
    /// `"shell"` (default) or `"claude"`.
    #[serde(default)]
    kind: Option<String>,
}

/// Arguments for `split_pane`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct SplitArgs {
    /// `"vertical"` (default, side by side) or `"horizontal"` (stacked).
    #[serde(default)]
    direction: Option<String>,
    /// Session handle to split. Omit for the focused pane.
    #[serde(default)]
    pane: Option<String>,
}

/// Arguments for `focus_pane`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct FocusArgs {
    /// The stable handle of the session to focus.
    session: String,
}

/// Arguments for `rename_tab`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct RenameArgs {
    /// 0-based tab index, as `snapshot` reports tab order.
    tab: usize,
    /// The new manual title; blank reverts to the derived title.
    title: String,
}

/// Arguments for `close_pane`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct CloseArgs {
    /// Session handle to close. Omit for the focused pane.
    #[serde(default)]
    pane: Option<String>,
}

/// Arguments for `run_in_session`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct RunArgs {
    /// The stable handle of the target session.
    session: String,
    /// Text to type; include a trailing newline to submit a command.
    text: String,
}

/// Parse a stable handle string (as `list_sessions` / `snapshot` report it) to
/// its numeric id, surfacing a non-numeric handle as an `invalid_params` error.
fn parse_handle(handle: &str) -> Result<u64, ErrorData> {
    handle
        .parse()
        .map_err(|_| ErrorData::invalid_params(format!("handle {handle:?} is not a number"), None))
}

/// Parse an optional handle: absent stays absent, present is validated.
fn parse_optional_handle(handle: Option<String>) -> Result<Option<u64>, ErrorData> {
    handle.map(|h| parse_handle(&h)).transpose()
}

/// Arguments for `wait_for_status`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct WaitArgs {
    /// The session handle to watch.
    session: String,
    /// Statuses that settle the wait. Omit for idle-or-attention.
    #[serde(default)]
    statuses: Option<Vec<String>>,
    /// How long to wait before reporting the current status instead.
    #[serde(default)]
    timeout_ms: Option<u64>,
}

/// Arguments for `read_terminal`.
#[derive(Debug, Default, Deserialize, JsonSchema)]
#[schemars(crate = "rmcp::schemars")]
struct ReadArgs {
    /// The session handle to read.
    session: String,
    /// Trailing lines to keep.
    #[serde(default)]
    lines: Option<usize>,
}

/// Map the named statuses onto the core enum. An empty or omitted list means
/// idle-or-attention — the two a caller waiting on a command actually wants.
/// An unknown name is rejected rather than dropped: silently waiting on fewer
/// statuses than asked is exactly the silent-catch trap to avoid.
fn parse_statuses(names: Option<Vec<String>>) -> Result<Vec<SessionStatus>, ErrorData> {
    let Some(names) = names.filter(|names| !names.is_empty()) else {
        return Ok(vec![SessionStatus::Idle, SessionStatus::Attention]);
    };
    names
        .iter()
        .map(|name| {
            status_from_str(name)
                .ok_or_else(|| ErrorData::invalid_params(format!("unknown status {name:?}"), None))
        })
        .collect()
}

/// The caller's bound for a wait, defaulted and capped. The cap is the outer
/// guarantee behind Q7: no bridge call, however it was parameterised, can park
/// a caller indefinitely.
fn wait_timeout(timeout_ms: Option<u64>) -> Duration {
    Duration::from_millis(timeout_ms.unwrap_or(DEFAULT_WAIT_MS).min(MAX_WAIT_MS))
}

/// The inverse of [`crate::snapshot_dto::status_str`] — the external word back
/// to the core enum.
fn status_from_str(name: &str) -> Option<SessionStatus> {
    match name {
        "starting" => Some(SessionStatus::Starting),
        "busy" => Some(SessionStatus::Busy),
        "idle" => Some(SessionStatus::Idle),
        "attention" => Some(SessionStatus::Attention),
        "exited" => Some(SessionStatus::Exited),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::shell::bridge::{Reply, Request, channel, spawn_test_shell};
    use termherd_core::{App, Event, Launch, LaunchSpec, SessionStatus, SnapshotInputs};

    #[tokio::test]
    async fn list_sessions_tool_shapes_the_bridge_reply_into_structured_json() {
        let (handle, requests) = channel();
        // Stand in for the shell: answer the ListSessions call with one session.
        let shell = spawn_test_shell(
            requests,
            Reply::Sessions(vec![SessionInfo {
                handle: "7".into(),
                title: "proj".into(),
                cwd: Some("/proj".into()),
                kind: SessionKind::Claude,
                resume_id: Some("claude-xyz".into()),
                status: SessionStatus::Busy,
            }]),
        );

        let result = TermherdMcp::new(handle)
            .list_sessions()
            .await
            .expect("the tool returns a result");

        assert_eq!(
            shell.await.expect("shell task"),
            Request::ListSessions,
            "the tool asked the bridge for the session list"
        );
        let rows = result
            .structured_content
            .expect("structured json content")
            .as_array()
            .cloned()
            .expect("an array of sessions");
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0]["handle"], "7", "the stable handle is carried out");
        assert_eq!(rows[0]["kind"], "claude");
        assert_eq!(rows[0]["status"], "busy");
        assert_eq!(
            rows[0]["resume_id"], "claude-xyz",
            "the Claude id rides alongside the handle, not as it"
        );
    }

    #[tokio::test]
    async fn list_sessions_tool_surfaces_a_bridge_failure_as_an_error() {
        // No shell answering: the bridge closes, and the tool must report an
        // error rather than hang (the silent-catch trap the substrate avoids).
        let (handle, requests) = channel();
        drop(requests);
        let error = TermherdMcp::new(handle)
            .list_sessions()
            .await
            .expect_err("a closed bridge is a tool error");
        assert!(
            error.message.contains("closed"),
            "the error names the closed bridge, got: {}",
            error.message
        );
    }

    #[test]
    fn snapshot_args_default_to_the_light_filter() {
        assert_eq!(
            SnapshotArgs::default().into_filter(),
            SnapshotFilter::default()
        );
    }

    #[test]
    fn snapshot_args_map_sections_terminals_and_text_lines() {
        let filter = SnapshotArgs {
            sections: Some(vec!["tabs".into(), "bogus".into()]),
            terminals: Some(vec!["3".into(), "4".into()]),
            text_lines: Some(10),
            ..SnapshotArgs::default()
        }
        .into_filter();
        // Unknown section names are dropped, not errors.
        assert_eq!(filter.sections, vec![Section::Tabs]);
        // String handles parse back to the numeric core scope.
        assert_eq!(filter.terminals, TerminalScope::Only(vec![3, 4]));
        assert_eq!(filter.text_lines, 10);
    }

    #[test]
    fn snapshot_args_with_empty_terminals_stay_text_free() {
        let filter = SnapshotArgs {
            terminals: Some(Vec::new()),
            ..SnapshotArgs::default()
        }
        .into_filter();
        assert_eq!(filter.terminals, TerminalScope::None);
    }

    #[test]
    fn snapshot_args_focused_terminal_shortcut_scopes_to_the_focused_pane() {
        let filter = SnapshotArgs {
            focused_terminal: Some(true),
            ..SnapshotArgs::default()
        }
        .into_filter();
        assert_eq!(filter.terminals, TerminalScope::Focused);

        // Explicit handles win over the shortcut.
        let filter = SnapshotArgs {
            terminals: Some(vec!["5".into()]),
            focused_terminal: Some(true),
            ..SnapshotArgs::default()
        }
        .into_filter();
        assert_eq!(filter.terminals, TerminalScope::Only(vec![5]));
    }

    #[tokio::test]
    async fn snapshot_tool_shapes_the_bridge_reply_into_structured_json() {
        // Answer with a real snapshot of a one-Claude-tab workspace.
        let mut app = App::new();
        app.apply(Event::LaunchSession(LaunchSpec {
            cwd: Some("/proj".into()),
            launch: Launch::Claude { resume: None },
            title: "work".into(),
        }));
        let filter = SnapshotFilter::default();
        let snapshot = app.snapshot(&filter, &SnapshotInputs::default());

        let (handle, requests) = channel();
        let shell = spawn_test_shell(requests, Reply::Snapshot(snapshot));
        let result = TermherdMcp::new(handle)
            .snapshot(Parameters(SnapshotArgs::default()))
            .await
            .expect("the tool returns a result");

        assert!(
            matches!(shell.await.expect("shell task"), Request::Snapshot(_)),
            "the tool asked the bridge for a snapshot"
        );
        let value = result.structured_content.expect("structured json content");
        // Handles are strings on the wire, matching `list_sessions`.
        assert_eq!(
            value["focus"]["session"], "1",
            "the launched session is focused"
        );
        assert_eq!(value["tabs"][0]["title"], "work");
        assert_eq!(value["tabs"][0]["panes"][0]["handle"], "1");
        assert_eq!(value["tabs"][0]["panes"][0]["kind"], "claude");
        assert_eq!(value["tabs"][0]["panes"][0]["cwd"], "/proj");
        // Light default: no terminal text was requested, so none is present.
        assert!(
            value.get("terminals").is_none(),
            "no terminal text by default"
        );
    }

    #[tokio::test]
    async fn snapshot_tool_surfaces_a_bridge_failure_as_an_error() {
        let (handle, requests) = channel();
        drop(requests);
        let error = TermherdMcp::new(handle)
            .snapshot(Parameters(SnapshotArgs::default()))
            .await
            .expect_err("a closed bridge is a tool error");
        assert!(error.message.contains("closed"), "got: {}", error.message);
    }

    // ---- Orchestration tools (F-mcp-orchestration) ----------------------

    use crate::shell::bridge::{Action, ActionOutcome};

    /// Run `call` against a shell that records the request and answers it with an
    /// applied outcome; return the `Action` the tool built.
    async fn action_of<F, Fut>(call: F) -> Action
    where
        F: FnOnce(TermherdMcp) -> Fut,
        Fut: std::future::Future<Output = Result<CallToolResult, ErrorData>>,
    {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(
            requests,
            Reply::Acted(ActionOutcome::applied(Some("2".into()))),
        );
        call(TermherdMcp::new(handle))
            .await
            .expect("the tool returns a result");
        match shell.await.expect("shell task") {
            Request::Act(action) => action,
            other => panic!("expected an action request, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn open_session_tool_builds_an_open_action() {
        let action = action_of(|mcp| async move {
            mcp.open_session(Parameters(OpenArgs {
                project: Some("/proj".into()),
                kind: Some("claude".into()),
            }))
            .await
        })
        .await;
        assert_eq!(
            action,
            Action::Open {
                project: Some("/proj".into()),
                kind: SessionKind::Claude,
            }
        );
    }

    #[tokio::test]
    async fn open_session_tool_defaults_kind_to_shell() {
        let action =
            action_of(|mcp| async move { mcp.open_session(Parameters(OpenArgs::default())).await })
                .await;
        assert_eq!(
            action,
            Action::Open {
                project: None,
                kind: SessionKind::Shell,
            }
        );
    }

    #[tokio::test]
    async fn open_session_tool_rejects_an_unknown_kind() {
        let (handle, requests) = channel();
        drop(requests); // never reached: the arg is rejected before the bridge.
        let error = TermherdMcp::new(handle)
            .open_session(Parameters(OpenArgs {
                project: None,
                kind: Some("wizard".into()),
            }))
            .await
            .expect_err("an unknown kind is an invalid_params error");
        assert!(error.message.contains("wizard"), "got: {}", error.message);
    }

    #[tokio::test]
    async fn split_pane_tool_maps_direction_and_target() {
        let action = action_of(|mcp| async move {
            mcp.split_pane(Parameters(SplitArgs {
                direction: Some("horizontal".into()),
                pane: Some("5".into()),
            }))
            .await
        })
        .await;
        assert_eq!(
            action,
            Action::Split {
                pane: Some(5),
                dir: SplitDir::Horizontal,
            }
        );
    }

    #[tokio::test]
    async fn split_pane_tool_defaults_to_a_vertical_split_of_the_focused_pane() {
        let action =
            action_of(|mcp| async move { mcp.split_pane(Parameters(SplitArgs::default())).await })
                .await;
        assert_eq!(
            action,
            Action::Split {
                pane: None,
                dir: SplitDir::Vertical,
            }
        );
    }

    #[tokio::test]
    async fn focus_and_run_tools_carry_the_parsed_handle() {
        let focus = action_of(|mcp| async move {
            mcp.focus_pane(Parameters(FocusArgs {
                session: "3".into(),
            }))
            .await
        })
        .await;
        assert_eq!(focus, Action::Focus { session: 3 });

        let run = action_of(|mcp| async move {
            mcp.run_in_session(Parameters(RunArgs {
                session: "3".into(),
                text: "ls\n".into(),
            }))
            .await
        })
        .await;
        assert_eq!(
            run,
            Action::Run {
                session: 3,
                bytes: b"ls\n".to_vec(),
            }
        );
    }

    #[tokio::test]
    async fn run_in_session_tool_rejects_a_non_numeric_handle() {
        let (handle, requests) = channel();
        drop(requests);
        let error = TermherdMcp::new(handle)
            .run_in_session(Parameters(RunArgs {
                session: "not-a-number".into(),
                text: "x".into(),
            }))
            .await
            .expect_err("a non-numeric handle is rejected before the bridge");
        assert!(
            error.message.contains("not-a-number"),
            "got: {}",
            error.message
        );
    }

    #[tokio::test]
    async fn rename_and_close_tools_build_their_actions() {
        let rename = action_of(|mcp| async move {
            mcp.rename_tab(Parameters(RenameArgs {
                tab: 1,
                title: "build".into(),
            }))
            .await
        })
        .await;
        assert_eq!(
            rename,
            Action::Rename {
                tab: 1,
                title: "build".into(),
            }
        );

        let close = action_of(|mcp| async move {
            mcp.close_pane(Parameters(CloseArgs {
                pane: Some("4".into()),
            }))
            .await
        })
        .await;
        assert_eq!(close, Action::Close { pane: Some(4) });
    }

    #[tokio::test]
    async fn a_tool_surfaces_a_rejected_action_as_invalid_params() {
        // The shell answers with a rejection (unknown handle); the tool must
        // relay it as an error, not a success with a null handle.
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(
            requests,
            Reply::Acted(ActionOutcome::rejected("no live session with handle 9")),
        );
        let error = TermherdMcp::new(handle)
            .focus_pane(Parameters(FocusArgs {
                session: "9".into(),
            }))
            .await
            .expect_err("a rejected action is a tool error");
        assert!(
            error.message.contains("handle 9"),
            "the rejection reason is relayed, got: {}",
            error.message
        );
    }

    #[tokio::test]
    async fn a_tool_reports_the_resulting_focus_on_success() {
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(
            requests,
            Reply::Acted(ActionOutcome::applied(Some("2".into()))),
        );
        let result = TermherdMcp::new(handle)
            .split_pane(Parameters(SplitArgs::default()))
            .await
            .expect("the tool returns a result");
        let value = result.structured_content.expect("structured json content");
        assert_eq!(
            value["focused_handle"], "2",
            "the new pane's handle is returned"
        );
    }

    #[tokio::test]
    async fn a_tool_surfaces_a_bridge_failure_as_an_error() {
        let (handle, requests) = channel();
        drop(requests);
        let error = TermherdMcp::new(handle)
            .close_pane(Parameters(CloseArgs::default()))
            .await
            .expect_err("a closed bridge is a tool error");
        assert!(error.message.contains("closed"), "got: {}", error.message);
    }

    // --- wait_for_status / read_terminal ---

    use crate::shell::bridge::{TerminalRead, WaitOutcome, spawn_test_shell_seq};

    /// Args for a wait on `session`, otherwise defaulted.
    fn wait_args(session: &str) -> WaitArgs {
        WaitArgs {
            session: session.to_owned(),
            ..WaitArgs::default()
        }
    }

    /// Run `wait_for_status` against a shell answering `reply`, returning the
    /// request the tool built.
    async fn wait_request(args: WaitArgs, reply: Reply) -> Request {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(requests, reply);
        let _ = TermherdMcp::new(handle)
            .wait_for_status(Parameters(args))
            .await;
        shell.await.expect("shell task")
    }

    /// A settled wait, as the shell would answer it.
    fn settled(status: SessionStatus) -> Reply {
        Reply::Waited(WaitOutcome {
            status: Some(status),
            error: None,
        })
    }

    #[tokio::test]
    async fn wait_for_status_defaults_to_idle_or_attention() {
        // The two a caller waiting on a command actually cares about: finished,
        // or stopped to ask something.
        let request = wait_request(wait_args("7"), settled(SessionStatus::Idle)).await;
        assert_eq!(
            request,
            Request::WaitForStatus {
                session: 7,
                targets: vec![SessionStatus::Idle, SessionStatus::Attention],
            }
        );
    }

    #[tokio::test]
    async fn wait_for_status_maps_the_named_statuses() {
        let args = WaitArgs {
            session: "7".into(),
            statuses: Some(vec!["busy".into(), "exited".into()]),
            ..WaitArgs::default()
        };
        let request = wait_request(args, settled(SessionStatus::Busy)).await;
        assert_eq!(
            request,
            Request::WaitForStatus {
                session: 7,
                targets: vec![SessionStatus::Busy, SessionStatus::Exited],
            }
        );
    }

    #[tokio::test]
    async fn wait_for_status_rejects_an_unknown_status_name() {
        // Dropping the unknown name and waiting on the rest would be the silent
        // catch this codebase exists to avoid.
        let (handle, requests) = channel();
        let args = WaitArgs {
            session: "7".into(),
            statuses: Some(vec!["idle".into(), "finished".into()]),
            ..WaitArgs::default()
        };
        let error = TermherdMcp::new(handle)
            .wait_for_status(Parameters(args))
            .await
            .expect_err("an unknown status is rejected");
        assert!(error.message.contains("finished"), "got: {}", error.message);
        drop(requests);
    }

    #[tokio::test]
    async fn wait_for_status_reports_the_settled_status() {
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(requests, settled(SessionStatus::Attention));
        let result = TermherdMcp::new(handle)
            .wait_for_status(Parameters(wait_args("7")))
            .await
            .expect("the tool returns a result");
        let value = result.structured_content.expect("structured json content");
        assert_eq!(value["status"], "attention");
        assert_eq!(value["timed_out"], false);
    }

    #[tokio::test]
    async fn wait_for_status_relays_an_unknown_handle_as_invalid_params() {
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(
            requests,
            Reply::Waited(WaitOutcome {
                status: None,
                error: Some("no live session with handle 7".into()),
            }),
        );
        let error = TermherdMcp::new(handle)
            .wait_for_status(Parameters(wait_args("7")))
            .await
            .expect_err("a rejected wait is a tool error");
        assert!(
            error.message.contains("no live session"),
            "got: {}",
            error.message
        );
    }

    #[tokio::test]
    async fn wait_for_status_reports_the_current_status_when_it_times_out() {
        // Timing out is not a failure: the agent needs to know *where* the
        // session got to, to decide between waiting again and giving up.
        let (handle, requests) = channel();
        let shell = spawn_test_shell_seq(
            requests,
            vec![
                // The wait itself: received, never answered.
                None,
                // The follow-up read of the current status.
                Some(Reply::Sessions(vec![SessionInfo {
                    handle: "7".into(),
                    title: "proj".into(),
                    cwd: None,
                    kind: SessionKind::Shell,
                    resume_id: None,
                    status: SessionStatus::Busy,
                }])),
            ],
        );
        let args = WaitArgs {
            session: "7".into(),
            timeout_ms: Some(50),
            ..WaitArgs::default()
        };
        let result = TermherdMcp::new(handle)
            .wait_for_status(Parameters(args))
            .await
            .expect("a timed-out wait still returns a result");
        let value = result.structured_content.expect("structured json content");
        assert_eq!(value["timed_out"], true);
        assert_eq!(
            value["status"], "busy",
            "the session's current status rides back with the timeout"
        );
        let seen = shell.await.expect("shell task");
        assert_eq!(seen.len(), 2, "the wait, then the status read-back");
        assert_eq!(seen[1], Request::ListSessions);
    }

    #[tokio::test]
    async fn a_wait_that_times_out_still_answers_when_the_read_back_fails() {
        // The likeliest cause of the original timeout is a wedged shell, which
        // fails the status read-back too. That must not swallow the `timed_out`
        // answer the caller already earned — it is the whole point of the path.
        let (handle, requests) = channel();
        // Neither the wait nor the read-back is ever answered.
        let shell = spawn_test_shell_seq(requests, vec![None, None]);
        let args = WaitArgs {
            session: "7".into(),
            timeout_ms: Some(50),
            ..WaitArgs::default()
        };
        let result = TermherdMcp::new(handle)
            .wait_for_status(Parameters(args))
            .await
            .expect("a wedged shell still yields the timeout answer");
        let value = result.structured_content.expect("structured json content");
        assert_eq!(value["timed_out"], true);
        assert!(
            value["status"].is_null(),
            "an unreadable status is null, not an error"
        );
        drop(shell);
    }

    #[test]
    fn a_wait_is_capped_however_long_the_caller_asks() {
        // The outer Q7 guarantee: no parameterisation parks a caller forever.
        assert_eq!(wait_timeout(None), Duration::from_millis(DEFAULT_WAIT_MS));
        assert_eq!(wait_timeout(Some(1_000)), Duration::from_millis(1_000));
        assert_eq!(
            wait_timeout(Some(u64::MAX)),
            Duration::from_millis(MAX_WAIT_MS)
        );
    }

    #[tokio::test]
    async fn read_terminal_passes_the_handle_and_line_budget() {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(
            requests,
            Reply::Terminal(TerminalRead {
                text: Some("$ cargo test".into()),
                error: None,
            }),
        );
        let result = TermherdMcp::new(handle)
            .read_terminal(Parameters(ReadArgs {
                session: "7".into(),
                lines: Some(5),
            }))
            .await
            .expect("the tool returns a result");
        assert_eq!(
            shell.await.expect("shell task"),
            Request::ReadTerminal {
                session: 7,
                lines: 5
            }
        );
        let value = result.structured_content.expect("structured json content");
        assert_eq!(value["text"], "$ cargo test");
        assert_eq!(value["rendered"], true);
    }

    #[tokio::test]
    async fn read_terminal_defaults_to_the_snapshot_line_budget() {
        let (handle, requests) = channel();
        let shell = spawn_test_shell(
            requests,
            Reply::Terminal(TerminalRead {
                text: None,
                error: None,
            }),
        );
        let _ = TermherdMcp::new(handle)
            .read_terminal(Parameters(ReadArgs {
                session: "7".into(),
                lines: None,
            }))
            .await;
        assert_eq!(
            shell.await.expect("shell task"),
            Request::ReadTerminal {
                session: 7,
                lines: DEFAULT_TEXT_LINES
            }
        );
    }

    #[tokio::test]
    async fn read_terminal_marks_an_undrawn_screen_as_not_rendered() {
        // Distinct from an unknown handle: the caller should retry, not give up.
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(
            requests,
            Reply::Terminal(TerminalRead {
                text: None,
                error: None,
            }),
        );
        let result = TermherdMcp::new(handle)
            .read_terminal(Parameters(ReadArgs {
                session: "7".into(),
                lines: None,
            }))
            .await
            .expect("an undrawn screen is not an error");
        let value = result.structured_content.expect("structured json content");
        assert_eq!(value["rendered"], false);
        assert_eq!(value["text"], "");
    }

    #[tokio::test]
    async fn read_terminal_relays_an_unknown_handle_as_invalid_params() {
        let (handle, requests) = channel();
        let _shell = spawn_test_shell(
            requests,
            Reply::Terminal(TerminalRead {
                text: None,
                error: Some("no live session with handle 7".into()),
            }),
        );
        let error = TermherdMcp::new(handle)
            .read_terminal(Parameters(ReadArgs {
                session: "7".into(),
                lines: None,
            }))
            .await
            .expect_err("a rejected read is a tool error");
        assert!(
            error.message.contains("no live session"),
            "got: {}",
            error.message
        );
    }
}
