//! The MCP tool surface exposed to hosted Claude sessions.
//!
//! [`TermherdMcp`] is an rmcp [`ServerHandler`]: it answers `tools/list` and
//! `tools/call` for the live-bridge tools. Each tool is a thin adapter — it
//! translates the call into a [`Request`] on the async-transport bridge, awaits
//! the timeout-bounded [`Reply`], and shapes it back into an MCP result. No state
//! and no `core` access live here; the shell owns `core::App` and answers on the
//! bridge, so a tool can never touch it directly.

use std::time::Duration;

use rmcp::{
    ErrorData, ServerHandler,
    handler::server::router::tool::ToolRouter,
    model::{CallToolResult, Implementation, ProtocolVersion, ServerCapabilities, ServerInfo},
    tool, tool_handler, tool_router,
};
use serde::Serialize;

use crate::shell::bridge::{BridgeHandle, Reply, Request, SessionInfo, SessionKind};

/// How long a tool waits for the shell to answer before failing the caller.
/// Bounds the whole round-trip (enqueue + reply) via [`BridgeHandle::call`], so
/// a wedged shell surfaces as a tool error, never a hang (Q7).
const CALL_TIMEOUT: Duration = Duration::from_secs(5);

/// The live-bridge MCP server handler. Holds only the bridge into the shell —
/// cloned fresh per session by the transport's service factory.
#[derive(Clone)]
pub struct TermherdMcp {
    bridge: BridgeHandle,
    tool_router: ToolRouter<Self>,
}

#[tool_router(router = tool_router)]
impl TermherdMcp {
    /// Build a handler over `bridge`. The tool router is generated by the
    /// `#[tool_router]` macro from the `#[tool]` methods below.
    pub fn new(bridge: BridgeHandle) -> Self {
        Self {
            bridge,
            tool_router: Self::tool_router(),
        }
    }

    /// The spike tool: list the live terminal sessions termherd is hosting, each
    /// with its stable handle, so an MCP client can address them.
    #[tool(
        name = "list_sessions",
        description = "List the live terminal sessions termherd is hosting. Each \
                       row carries a stable `handle` (address it in later calls), \
                       the tab title, working directory, kind (shell or claude), \
                       the resumed Claude id if any, and current activity status."
    )]
    async fn list_sessions(&self) -> Result<CallToolResult, ErrorData> {
        let reply = self
            .bridge
            .call(Request::ListSessions, CALL_TIMEOUT)
            .await
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        let Reply::Sessions(sessions) = reply else {
            return Err(ErrorData::internal_error(
                "bridge answered the wrong reply kind",
                None,
            ));
        };
        let rows: Vec<SessionDto> = sessions.iter().map(SessionDto::from).collect();
        let value = serde_json::to_value(&rows)
            .map_err(|error| ErrorData::internal_error(error.to_string(), None))?;
        Ok(CallToolResult::structured(value))
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for TermherdMcp {
    fn get_info(&self) -> ServerInfo {
        // rmcp's `ServerInfo`/`Implementation` are `#[non_exhaustive]`, so build
        // from a default and set the fields we care about rather than a literal.
        let mut server = Implementation::from_build_env();
        server.name = "termherd".into();
        server.version = env!("CARGO_PKG_VERSION").into();

        let mut info = ServerInfo::default();
        info.protocol_version = ProtocolVersion::LATEST;
        info.capabilities = ServerCapabilities::builder().enable_tools().build();
        info.server_info = server;
        info.instructions = Some(
            "termherd's live bridge: read and (later) drive the terminal \
             sessions it is hosting."
                .into(),
        );
        info
    }
}

/// The on-the-wire shape of a session for the `list_sessions` tool: the stable
/// external handle plus flat, string-typed fields an MCP client can read without
/// knowing termherd's internal enums.
#[derive(Serialize)]
struct SessionDto {
    /// Stable external handle (the runtime session id).
    handle: String,
    title: String,
    cwd: Option<String>,
    /// `"shell"` or `"claude"`.
    kind: &'static str,
    /// The resumed Claude session id, if any (the *unstable* id — never the
    /// handle).
    resume_id: Option<String>,
    /// `"starting"`, `"busy"`, `"idle"`, `"attention"`, or `"exited"`.
    status: &'static str,
}

impl From<&SessionInfo> for SessionDto {
    fn from(info: &SessionInfo) -> Self {
        use termherd_core::SessionStatus::*;
        Self {
            handle: info.handle.clone(),
            title: info.title.clone(),
            cwd: info.cwd.clone(),
            kind: match info.kind {
                SessionKind::Shell => "shell",
                SessionKind::Claude => "claude",
            },
            resume_id: info.resume_id.clone(),
            status: match info.status {
                Starting => "starting",
                Busy => "busy",
                Idle => "idle",
                Attention => "attention",
                Exited => "exited",
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::shell::bridge::{Reply, Request, channel, spawn_test_shell};
    use termherd_core::SessionStatus;

    #[tokio::test]
    async fn list_sessions_tool_shapes_the_bridge_reply_into_structured_json() {
        let (handle, requests) = channel();
        // Stand in for the shell: answer the ListSessions call with one session.
        let shell = spawn_test_shell(
            requests,
            Reply::Sessions(vec![SessionInfo {
                handle: "7".into(),
                title: "proj".into(),
                cwd: Some("/proj".into()),
                kind: SessionKind::Claude,
                resume_id: Some("claude-xyz".into()),
                status: SessionStatus::Busy,
            }]),
        );

        let result = TermherdMcp::new(handle)
            .list_sessions()
            .await
            .expect("the tool returns a result");

        assert_eq!(
            shell.await.expect("shell task"),
            Request::ListSessions,
            "the tool asked the bridge for the session list"
        );
        let rows = result
            .structured_content
            .expect("structured json content")
            .as_array()
            .cloned()
            .expect("an array of sessions");
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0]["handle"], "7", "the stable handle is carried out");
        assert_eq!(rows[0]["kind"], "claude");
        assert_eq!(rows[0]["status"], "busy");
        assert_eq!(
            rows[0]["resume_id"], "claude-xyz",
            "the Claude id rides alongside the handle, not as it"
        );
    }

    #[tokio::test]
    async fn list_sessions_tool_surfaces_a_bridge_failure_as_an_error() {
        // No shell answering: the bridge closes, and the tool must report an
        // error rather than hang (the silent-catch trap the substrate avoids).
        let (handle, requests) = channel();
        drop(requests);
        let error = TermherdMcp::new(handle)
            .list_sessions()
            .await
            .expect_err("a closed bridge is a tool error");
        assert!(
            error.message.contains("closed"),
            "the error names the closed bridge, got: {}",
            error.message
        );
    }
}
